/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDisputeFHE,
  IDisputeFHEInterface,
} from "../../interfaces/IDisputeFHE";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
    ],
    name: "DisputeAlreadyExists",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "disputeId",
        type: "bytes32",
      },
    ],
    name: "DisputeAlreadyResolved",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "disputeId",
        type: "bytes32",
      },
    ],
    name: "DisputeNotFound",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "disputeId",
        type: "bytes32",
      },
    ],
    name: "DisputeNotOpen",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidResolution",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidResolutionDeadline",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
    ],
    name: "InvoiceNotEscrowed",
    type: "error",
  },
  {
    inputs: [],
    name: "UnauthorizedCaller",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "disputeId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "disputant",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "arbiter",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "reasonHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "resolutionDeadline",
        type: "uint64",
      },
    ],
    name: "DisputeRaised",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "disputeId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "arbiter",
        type: "address",
      },
      {
        indexed: false,
        internalType: "enum IDisputeFHE.DisputeStatus",
        name: "resolution",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "resolutionHash",
        type: "bytes32",
      },
    ],
    name: "DisputeResolved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "disputeId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "submitter",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "newEvidenceHash",
        type: "bytes32",
      },
    ],
    name: "EvidenceSubmitted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "disputeId",
        type: "bytes32",
      },
    ],
    name: "getDispute",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "disputeId",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "invoiceId",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "disputant",
            type: "address",
          },
          {
            internalType: "address",
            name: "arbiter",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "reasonHash",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "evidenceHash",
            type: "bytes32",
          },
          {
            internalType: "enum IDisputeFHE.DisputeStatus",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "uint64",
            name: "createdAt",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "resolutionDeadline",
            type: "uint64",
          },
        ],
        internalType: "struct IDisputeFHE.DisputeData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
    ],
    name: "getDisputeByInvoice",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "arbiter",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "reasonHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "evidenceHash",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "resolutionDeadline",
        type: "uint64",
      },
    ],
    name: "raiseDispute",
    outputs: [
      {
        internalType: "bytes32",
        name: "disputeId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "disputeId",
        type: "bytes32",
      },
      {
        internalType: "enum IDisputeFHE.DisputeStatus",
        name: "resolution",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "resolutionHash",
        type: "bytes32",
      },
    ],
    name: "resolveDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "disputeId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "newEvidenceHash",
        type: "bytes32",
      },
    ],
    name: "submitEvidence",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDisputeFHE__factory {
  static readonly abi = _abi;
  static createInterface(): IDisputeFHEInterface {
    return new Interface(_abi) as IDisputeFHEInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IDisputeFHE {
    return new Contract(address, _abi, runner) as unknown as IDisputeFHE;
  }
}
