/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IInvoiceRegistryFHE,
  IInvoiceRegistryFHEInterface,
} from "../../interfaces/IInvoiceRegistryFHE";

const _abi = [
  {
    inputs: [],
    name: "InvalidRelayer",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidStatus",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "currentStatus",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "newStatus",
        type: "uint8",
      },
    ],
    name: "InvalidStatusTransition",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
    ],
    name: "InvoiceAlreadyExists",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
    ],
    name: "InvoiceNotFound",
    type: "error",
  },
  {
    inputs: [],
    name: "UnauthorizedCaller",
    type: "error",
  },
  {
    inputs: [],
    name: "UnauthorizedRelayer",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "cancelledBy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "cancelledAt",
        type: "uint64",
      },
    ],
    name: "InvoiceCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "seller",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "invoiceHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "dueDate",
        type: "uint64",
      },
    ],
    name: "InvoiceCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "paidAt",
        type: "uint64",
      },
    ],
    name: "InvoicePaid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "enum IInvoiceRegistryFHE.InvoiceStatus",
        name: "previousStatus",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "enum IInvoiceRegistryFHE.InvoiceStatus",
        name: "newStatus",
        type: "uint8",
      },
    ],
    name: "InvoiceStatusUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousRelayer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newRelayer",
        type: "address",
      },
    ],
    name: "RelayerUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
    ],
    name: "cancelInvoice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "seller",
        type: "address",
      },
      {
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "invoiceHash",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "dueDate",
        type: "uint64",
      },
      {
        internalType: "bool",
        name: "hasEscrow",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "hasDispute",
        type: "bool",
      },
    ],
    name: "createInvoice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
    ],
    name: "getInvoice",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "seller",
            type: "address",
          },
          {
            internalType: "address",
            name: "buyer",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "invoiceId",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "invoiceHash",
            type: "bytes32",
          },
          {
            internalType: "uint64",
            name: "dueDate",
            type: "uint64",
          },
          {
            internalType: "enum IInvoiceRegistryFHE.InvoiceStatus",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "hasEscrow",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "hasDispute",
            type: "bool",
          },
          {
            internalType: "uint64",
            name: "createdAt",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "updatedAt",
            type: "uint64",
          },
        ],
        internalType: "struct IInvoiceRegistryFHE.InvoiceHeader",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
    ],
    name: "getInvoiceStatus",
    outputs: [
      {
        internalType: "enum IInvoiceRegistryFHE.InvoiceStatus",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
    ],
    name: "invoiceExists",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
    ],
    name: "markAsPaid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
    ],
    name: "payInvoice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "relayer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
      {
        internalType: "bool",
        name: "authorized",
        type: "bool",
      },
    ],
    name: "setAuthorizedContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newRelayer",
        type: "address",
      },
    ],
    name: "setRelayer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
      {
        internalType: "enum IInvoiceRegistryFHE.InvoiceStatus",
        name: "newStatus",
        type: "uint8",
      },
    ],
    name: "updateInvoiceStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IInvoiceRegistryFHE__factory {
  static readonly abi = _abi;
  static createInterface(): IInvoiceRegistryFHEInterface {
    return new Interface(_abi) as IInvoiceRegistryFHEInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IInvoiceRegistryFHE {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IInvoiceRegistryFHE;
  }
}
