/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "DisputeFHE",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DisputeFHE__factory>;
    getContractFactory(
      name: "EscrowFHE",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EscrowFHE__factory>;
    getContractFactory(
      name: "IDisputeFHE",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDisputeFHE__factory>;
    getContractFactory(
      name: "IEscrowFHE",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IEscrowFHE__factory>;
    getContractFactory(
      name: "IInvoiceRegistryFHE",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IInvoiceRegistryFHE__factory>;
    getContractFactory(
      name: "InvoiceRegistryFHE",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InvoiceRegistryFHE__factory>;

    getContractAt(
      name: "DisputeFHE",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DisputeFHE>;
    getContractAt(
      name: "EscrowFHE",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EscrowFHE>;
    getContractAt(
      name: "IDisputeFHE",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDisputeFHE>;
    getContractAt(
      name: "IEscrowFHE",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IEscrowFHE>;
    getContractAt(
      name: "IInvoiceRegistryFHE",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IInvoiceRegistryFHE>;
    getContractAt(
      name: "InvoiceRegistryFHE",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.InvoiceRegistryFHE>;

    deployContract(
      name: "DisputeFHE",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DisputeFHE>;
    deployContract(
      name: "EscrowFHE",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowFHE>;
    deployContract(
      name: "IDisputeFHE",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDisputeFHE>;
    deployContract(
      name: "IEscrowFHE",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEscrowFHE>;
    deployContract(
      name: "IInvoiceRegistryFHE",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInvoiceRegistryFHE>;
    deployContract(
      name: "InvoiceRegistryFHE",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InvoiceRegistryFHE>;

    deployContract(
      name: "DisputeFHE",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DisputeFHE>;
    deployContract(
      name: "EscrowFHE",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowFHE>;
    deployContract(
      name: "IDisputeFHE",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDisputeFHE>;
    deployContract(
      name: "IEscrowFHE",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEscrowFHE>;
    deployContract(
      name: "IInvoiceRegistryFHE",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInvoiceRegistryFHE>;
    deployContract(
      name: "InvoiceRegistryFHE",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InvoiceRegistryFHE>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
