/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IDisputeFHE {
  export type DisputeDataStruct = {
    disputeId: BytesLike;
    invoiceId: BytesLike;
    disputant: AddressLike;
    arbiter: AddressLike;
    reasonHash: BytesLike;
    evidenceHash: BytesLike;
    status: BigNumberish;
    createdAt: BigNumberish;
    resolutionDeadline: BigNumberish;
  };

  export type DisputeDataStructOutput = [
    disputeId: string,
    invoiceId: string,
    disputant: string,
    arbiter: string,
    reasonHash: string,
    evidenceHash: string,
    status: bigint,
    createdAt: bigint,
    resolutionDeadline: bigint
  ] & {
    disputeId: string;
    invoiceId: string;
    disputant: string;
    arbiter: string;
    reasonHash: string;
    evidenceHash: string;
    status: bigint;
    createdAt: bigint;
    resolutionDeadline: bigint;
  };
}

export interface IDisputeFHEInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getDispute"
      | "getDisputeByInvoice"
      | "raiseDispute"
      | "resolveDispute"
      | "submitEvidence"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeRaised"
      | "DisputeResolved"
      | "EvidenceSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getDispute",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDisputeByInvoice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BytesLike, AddressLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEvidence",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getDispute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDisputeByInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEvidence",
    data: BytesLike
  ): Result;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [
    disputeId: BytesLike,
    invoiceId: BytesLike,
    disputant: AddressLike,
    arbiter: AddressLike,
    reasonHash: BytesLike,
    resolutionDeadline: BigNumberish
  ];
  export type OutputTuple = [
    disputeId: string,
    invoiceId: string,
    disputant: string,
    arbiter: string,
    reasonHash: string,
    resolutionDeadline: bigint
  ];
  export interface OutputObject {
    disputeId: string;
    invoiceId: string;
    disputant: string;
    arbiter: string;
    reasonHash: string;
    resolutionDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    disputeId: BytesLike,
    invoiceId: BytesLike,
    arbiter: AddressLike,
    resolution: BigNumberish,
    resolutionHash: BytesLike
  ];
  export type OutputTuple = [
    disputeId: string,
    invoiceId: string,
    arbiter: string,
    resolution: bigint,
    resolutionHash: string
  ];
  export interface OutputObject {
    disputeId: string;
    invoiceId: string;
    arbiter: string;
    resolution: bigint;
    resolutionHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceSubmittedEvent {
  export type InputTuple = [
    disputeId: BytesLike,
    submitter: AddressLike,
    newEvidenceHash: BytesLike
  ];
  export type OutputTuple = [
    disputeId: string,
    submitter: string,
    newEvidenceHash: string
  ];
  export interface OutputObject {
    disputeId: string;
    submitter: string;
    newEvidenceHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDisputeFHE extends BaseContract {
  connect(runner?: ContractRunner | null): IDisputeFHE;
  waitForDeployment(): Promise<this>;

  interface: IDisputeFHEInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getDispute: TypedContractMethod<
    [disputeId: BytesLike],
    [IDisputeFHE.DisputeDataStructOutput],
    "view"
  >;

  getDisputeByInvoice: TypedContractMethod<
    [invoiceId: BytesLike],
    [string],
    "view"
  >;

  raiseDispute: TypedContractMethod<
    [
      invoiceId: BytesLike,
      arbiter: AddressLike,
      reasonHash: BytesLike,
      evidenceHash: BytesLike,
      resolutionDeadline: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [disputeId: BytesLike, resolution: BigNumberish, resolutionHash: BytesLike],
    [void],
    "nonpayable"
  >;

  submitEvidence: TypedContractMethod<
    [disputeId: BytesLike, newEvidenceHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getDispute"
  ): TypedContractMethod<
    [disputeId: BytesLike],
    [IDisputeFHE.DisputeDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDisputeByInvoice"
  ): TypedContractMethod<[invoiceId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<
    [
      invoiceId: BytesLike,
      arbiter: AddressLike,
      reasonHash: BytesLike,
      evidenceHash: BytesLike,
      resolutionDeadline: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [disputeId: BytesLike, resolution: BigNumberish, resolutionHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitEvidence"
  ): TypedContractMethod<
    [disputeId: BytesLike, newEvidenceHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceSubmitted"
  ): TypedContractEvent<
    EvidenceSubmittedEvent.InputTuple,
    EvidenceSubmittedEvent.OutputTuple,
    EvidenceSubmittedEvent.OutputObject
  >;

  filters: {
    "DisputeRaised(bytes32,bytes32,address,address,bytes32,uint64)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(bytes32,bytes32,address,uint8,bytes32)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "EvidenceSubmitted(bytes32,address,bytes32)": TypedContractEvent<
      EvidenceSubmittedEvent.InputTuple,
      EvidenceSubmittedEvent.OutputTuple,
      EvidenceSubmittedEvent.OutputObject
    >;
    EvidenceSubmitted: TypedContractEvent<
      EvidenceSubmittedEvent.InputTuple,
      EvidenceSubmittedEvent.OutputTuple,
      EvidenceSubmittedEvent.OutputObject
    >;
  };
}
