/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IEscrowFHE {
  export type EscrowDataStruct = {
    escrowId: BytesLike;
    invoiceId: BytesLike;
    payer: AddressLike;
    payee: AddressLike;
    amount: BigNumberish;
    deliveryDeadline: BigNumberish;
    arbiter: AddressLike;
    status: BigNumberish;
    createdAt: BigNumberish;
  };

  export type EscrowDataStructOutput = [
    escrowId: string,
    invoiceId: string,
    payer: string,
    payee: string,
    amount: bigint,
    deliveryDeadline: bigint,
    arbiter: string,
    status: bigint,
    createdAt: bigint
  ] & {
    escrowId: string;
    invoiceId: string;
    payer: string;
    payee: string;
    amount: bigint;
    deliveryDeadline: bigint;
    arbiter: string;
    status: bigint;
    createdAt: bigint;
  };
}

export interface IEscrowFHEInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "arbiterResolve"
      | "confirmDelivery"
      | "createEscrow"
      | "getEscrow"
      | "getEscrowByInvoice"
      | "isAuthorizedResolver"
      | "setAuthorizedResolver"
      | "timeoutRefund"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArbiterResolved"
      | "AuthorizedResolverUpdated"
      | "EscrowCreated"
      | "EscrowRefunded"
      | "EscrowReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "arbiterResolve",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmDelivery",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [BytesLike, AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrowByInvoice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedResolver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedResolver",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "timeoutRefund",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "arbiterResolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEscrowByInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeoutRefund",
    data: BytesLike
  ): Result;
}

export namespace ArbiterResolvedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    invoiceId: BytesLike,
    arbiter: AddressLike,
    releasedToSeller: boolean
  ];
  export type OutputTuple = [
    escrowId: string,
    invoiceId: string,
    arbiter: string,
    releasedToSeller: boolean
  ];
  export interface OutputObject {
    escrowId: string;
    invoiceId: string;
    arbiter: string;
    releasedToSeller: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuthorizedResolverUpdatedEvent {
  export type InputTuple = [resolver: AddressLike, authorized: boolean];
  export type OutputTuple = [resolver: string, authorized: boolean];
  export interface OutputObject {
    resolver: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    invoiceId: BytesLike,
    payer: AddressLike,
    payee: AddressLike,
    deliveryDeadline: BigNumberish,
    arbiter: AddressLike
  ];
  export type OutputTuple = [
    escrowId: string,
    invoiceId: string,
    payer: string,
    payee: string,
    deliveryDeadline: bigint,
    arbiter: string
  ];
  export interface OutputObject {
    escrowId: string;
    invoiceId: string;
    payer: string;
    payee: string;
    deliveryDeadline: bigint;
    arbiter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    invoiceId: BytesLike,
    payer: AddressLike,
    refundedAt: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: string,
    invoiceId: string,
    payer: string,
    refundedAt: bigint
  ];
  export interface OutputObject {
    escrowId: string;
    invoiceId: string;
    payer: string;
    refundedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    invoiceId: BytesLike,
    payee: AddressLike,
    releasedAt: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: string,
    invoiceId: string,
    payee: string,
    releasedAt: bigint
  ];
  export interface OutputObject {
    escrowId: string;
    invoiceId: string;
    payee: string;
    releasedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IEscrowFHE extends BaseContract {
  connect(runner?: ContractRunner | null): IEscrowFHE;
  waitForDeployment(): Promise<this>;

  interface: IEscrowFHEInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  arbiterResolve: TypedContractMethod<
    [escrowId: BytesLike, releaseToSeller: boolean],
    [void],
    "nonpayable"
  >;

  confirmDelivery: TypedContractMethod<
    [escrowId: BytesLike],
    [void],
    "nonpayable"
  >;

  createEscrow: TypedContractMethod<
    [
      invoiceId: BytesLike,
      payee: AddressLike,
      deliveryDeadline: BigNumberish,
      arbiter: AddressLike
    ],
    [string],
    "payable"
  >;

  getEscrow: TypedContractMethod<
    [escrowId: BytesLike],
    [IEscrowFHE.EscrowDataStructOutput],
    "view"
  >;

  getEscrowByInvoice: TypedContractMethod<
    [invoiceId: BytesLike],
    [string],
    "view"
  >;

  isAuthorizedResolver: TypedContractMethod<
    [resolver: AddressLike],
    [boolean],
    "view"
  >;

  setAuthorizedResolver: TypedContractMethod<
    [resolver: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  timeoutRefund: TypedContractMethod<
    [escrowId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "arbiterResolve"
  ): TypedContractMethod<
    [escrowId: BytesLike, releaseToSeller: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confirmDelivery"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [
      invoiceId: BytesLike,
      payee: AddressLike,
      deliveryDeadline: BigNumberish,
      arbiter: AddressLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [escrowId: BytesLike],
    [IEscrowFHE.EscrowDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEscrowByInvoice"
  ): TypedContractMethod<[invoiceId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "isAuthorizedResolver"
  ): TypedContractMethod<[resolver: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setAuthorizedResolver"
  ): TypedContractMethod<
    [resolver: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "timeoutRefund"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "ArbiterResolved"
  ): TypedContractEvent<
    ArbiterResolvedEvent.InputTuple,
    ArbiterResolvedEvent.OutputTuple,
    ArbiterResolvedEvent.OutputObject
  >;
  getEvent(
    key: "AuthorizedResolverUpdated"
  ): TypedContractEvent<
    AuthorizedResolverUpdatedEvent.InputTuple,
    AuthorizedResolverUpdatedEvent.OutputTuple,
    AuthorizedResolverUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;

  filters: {
    "ArbiterResolved(bytes32,bytes32,address,bool)": TypedContractEvent<
      ArbiterResolvedEvent.InputTuple,
      ArbiterResolvedEvent.OutputTuple,
      ArbiterResolvedEvent.OutputObject
    >;
    ArbiterResolved: TypedContractEvent<
      ArbiterResolvedEvent.InputTuple,
      ArbiterResolvedEvent.OutputTuple,
      ArbiterResolvedEvent.OutputObject
    >;

    "AuthorizedResolverUpdated(address,bool)": TypedContractEvent<
      AuthorizedResolverUpdatedEvent.InputTuple,
      AuthorizedResolverUpdatedEvent.OutputTuple,
      AuthorizedResolverUpdatedEvent.OutputObject
    >;
    AuthorizedResolverUpdated: TypedContractEvent<
      AuthorizedResolverUpdatedEvent.InputTuple,
      AuthorizedResolverUpdatedEvent.OutputTuple,
      AuthorizedResolverUpdatedEvent.OutputObject
    >;

    "EscrowCreated(bytes32,bytes32,address,address,uint64,address)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "EscrowRefunded(bytes32,bytes32,address,uint64)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "EscrowReleased(bytes32,bytes32,address,uint64)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
  };
}
