/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IInvoiceRegistryFHE {
  export type InvoiceHeaderStruct = {
    seller: AddressLike;
    buyer: AddressLike;
    invoiceId: BytesLike;
    invoiceHash: BytesLike;
    dueDate: BigNumberish;
    status: BigNumberish;
    hasEscrow: boolean;
    hasDispute: boolean;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type InvoiceHeaderStructOutput = [
    seller: string,
    buyer: string,
    invoiceId: string,
    invoiceHash: string,
    dueDate: bigint,
    status: bigint,
    hasEscrow: boolean,
    hasDispute: boolean,
    createdAt: bigint,
    updatedAt: bigint
  ] & {
    seller: string;
    buyer: string;
    invoiceId: string;
    invoiceHash: string;
    dueDate: bigint;
    status: bigint;
    hasEscrow: boolean;
    hasDispute: boolean;
    createdAt: bigint;
    updatedAt: bigint;
  };
}

export interface IInvoiceRegistryFHEInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelInvoice"
      | "createInvoice"
      | "getInvoice"
      | "getInvoiceStatus"
      | "invoiceExists"
      | "markAsPaid"
      | "payInvoice"
      | "relayer"
      | "setAuthorizedContract"
      | "setRelayer"
      | "updateInvoiceStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "InvoiceCancelled"
      | "InvoiceCreated"
      | "InvoicePaid"
      | "InvoiceStatusUpdated"
      | "RelayerUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelInvoice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createInvoice",
    values: [
      AddressLike,
      AddressLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      boolean,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvoice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvoiceStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "invoiceExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markAsPaid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "payInvoice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedContract",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateInvoiceStatus",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getInvoice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getInvoiceStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invoiceExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markAsPaid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payInvoice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRelayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateInvoiceStatus",
    data: BytesLike
  ): Result;
}

export namespace InvoiceCancelledEvent {
  export type InputTuple = [
    invoiceId: BytesLike,
    cancelledBy: AddressLike,
    cancelledAt: BigNumberish
  ];
  export type OutputTuple = [
    invoiceId: string,
    cancelledBy: string,
    cancelledAt: bigint
  ];
  export interface OutputObject {
    invoiceId: string;
    cancelledBy: string;
    cancelledAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoiceCreatedEvent {
  export type InputTuple = [
    invoiceId: BytesLike,
    seller: AddressLike,
    buyer: AddressLike,
    invoiceHash: BytesLike,
    dueDate: BigNumberish
  ];
  export type OutputTuple = [
    invoiceId: string,
    seller: string,
    buyer: string,
    invoiceHash: string,
    dueDate: bigint
  ];
  export interface OutputObject {
    invoiceId: string;
    seller: string;
    buyer: string;
    invoiceHash: string;
    dueDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoicePaidEvent {
  export type InputTuple = [
    invoiceId: BytesLike,
    payer: AddressLike,
    paidAt: BigNumberish
  ];
  export type OutputTuple = [invoiceId: string, payer: string, paidAt: bigint];
  export interface OutputObject {
    invoiceId: string;
    payer: string;
    paidAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoiceStatusUpdatedEvent {
  export type InputTuple = [
    invoiceId: BytesLike,
    previousStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    invoiceId: string,
    previousStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    invoiceId: string;
    previousStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerUpdatedEvent {
  export type InputTuple = [
    previousRelayer: AddressLike,
    newRelayer: AddressLike
  ];
  export type OutputTuple = [previousRelayer: string, newRelayer: string];
  export interface OutputObject {
    previousRelayer: string;
    newRelayer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IInvoiceRegistryFHE extends BaseContract {
  connect(runner?: ContractRunner | null): IInvoiceRegistryFHE;
  waitForDeployment(): Promise<this>;

  interface: IInvoiceRegistryFHEInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelInvoice: TypedContractMethod<
    [invoiceId: BytesLike],
    [void],
    "nonpayable"
  >;

  createInvoice: TypedContractMethod<
    [
      seller: AddressLike,
      buyer: AddressLike,
      invoiceId: BytesLike,
      invoiceHash: BytesLike,
      dueDate: BigNumberish,
      hasEscrow: boolean,
      hasDispute: boolean
    ],
    [void],
    "nonpayable"
  >;

  getInvoice: TypedContractMethod<
    [invoiceId: BytesLike],
    [IInvoiceRegistryFHE.InvoiceHeaderStructOutput],
    "view"
  >;

  getInvoiceStatus: TypedContractMethod<
    [invoiceId: BytesLike],
    [bigint],
    "view"
  >;

  invoiceExists: TypedContractMethod<[invoiceId: BytesLike], [boolean], "view">;

  markAsPaid: TypedContractMethod<[invoiceId: BytesLike], [void], "nonpayable">;

  payInvoice: TypedContractMethod<[invoiceId: BytesLike], [void], "nonpayable">;

  relayer: TypedContractMethod<[], [string], "view">;

  setAuthorizedContract: TypedContractMethod<
    [contractAddress: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  setRelayer: TypedContractMethod<
    [newRelayer: AddressLike],
    [void],
    "nonpayable"
  >;

  updateInvoiceStatus: TypedContractMethod<
    [invoiceId: BytesLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelInvoice"
  ): TypedContractMethod<[invoiceId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createInvoice"
  ): TypedContractMethod<
    [
      seller: AddressLike,
      buyer: AddressLike,
      invoiceId: BytesLike,
      invoiceHash: BytesLike,
      dueDate: BigNumberish,
      hasEscrow: boolean,
      hasDispute: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getInvoice"
  ): TypedContractMethod<
    [invoiceId: BytesLike],
    [IInvoiceRegistryFHE.InvoiceHeaderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInvoiceStatus"
  ): TypedContractMethod<[invoiceId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "invoiceExists"
  ): TypedContractMethod<[invoiceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "markAsPaid"
  ): TypedContractMethod<[invoiceId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "payInvoice"
  ): TypedContractMethod<[invoiceId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "relayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAuthorizedContract"
  ): TypedContractMethod<
    [contractAddress: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRelayer"
  ): TypedContractMethod<[newRelayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateInvoiceStatus"
  ): TypedContractMethod<
    [invoiceId: BytesLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "InvoiceCancelled"
  ): TypedContractEvent<
    InvoiceCancelledEvent.InputTuple,
    InvoiceCancelledEvent.OutputTuple,
    InvoiceCancelledEvent.OutputObject
  >;
  getEvent(
    key: "InvoiceCreated"
  ): TypedContractEvent<
    InvoiceCreatedEvent.InputTuple,
    InvoiceCreatedEvent.OutputTuple,
    InvoiceCreatedEvent.OutputObject
  >;
  getEvent(
    key: "InvoicePaid"
  ): TypedContractEvent<
    InvoicePaidEvent.InputTuple,
    InvoicePaidEvent.OutputTuple,
    InvoicePaidEvent.OutputObject
  >;
  getEvent(
    key: "InvoiceStatusUpdated"
  ): TypedContractEvent<
    InvoiceStatusUpdatedEvent.InputTuple,
    InvoiceStatusUpdatedEvent.OutputTuple,
    InvoiceStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RelayerUpdated"
  ): TypedContractEvent<
    RelayerUpdatedEvent.InputTuple,
    RelayerUpdatedEvent.OutputTuple,
    RelayerUpdatedEvent.OutputObject
  >;

  filters: {
    "InvoiceCancelled(bytes32,address,uint64)": TypedContractEvent<
      InvoiceCancelledEvent.InputTuple,
      InvoiceCancelledEvent.OutputTuple,
      InvoiceCancelledEvent.OutputObject
    >;
    InvoiceCancelled: TypedContractEvent<
      InvoiceCancelledEvent.InputTuple,
      InvoiceCancelledEvent.OutputTuple,
      InvoiceCancelledEvent.OutputObject
    >;

    "InvoiceCreated(bytes32,address,address,bytes32,uint64)": TypedContractEvent<
      InvoiceCreatedEvent.InputTuple,
      InvoiceCreatedEvent.OutputTuple,
      InvoiceCreatedEvent.OutputObject
    >;
    InvoiceCreated: TypedContractEvent<
      InvoiceCreatedEvent.InputTuple,
      InvoiceCreatedEvent.OutputTuple,
      InvoiceCreatedEvent.OutputObject
    >;

    "InvoicePaid(bytes32,address,uint64)": TypedContractEvent<
      InvoicePaidEvent.InputTuple,
      InvoicePaidEvent.OutputTuple,
      InvoicePaidEvent.OutputObject
    >;
    InvoicePaid: TypedContractEvent<
      InvoicePaidEvent.InputTuple,
      InvoicePaidEvent.OutputTuple,
      InvoicePaidEvent.OutputObject
    >;

    "InvoiceStatusUpdated(bytes32,uint8,uint8)": TypedContractEvent<
      InvoiceStatusUpdatedEvent.InputTuple,
      InvoiceStatusUpdatedEvent.OutputTuple,
      InvoiceStatusUpdatedEvent.OutputObject
    >;
    InvoiceStatusUpdated: TypedContractEvent<
      InvoiceStatusUpdatedEvent.InputTuple,
      InvoiceStatusUpdatedEvent.OutputTuple,
      InvoiceStatusUpdatedEvent.OutputObject
    >;

    "RelayerUpdated(address,address)": TypedContractEvent<
      RelayerUpdatedEvent.InputTuple,
      RelayerUpdatedEvent.OutputTuple,
      RelayerUpdatedEvent.OutputObject
    >;
    RelayerUpdated: TypedContractEvent<
      RelayerUpdatedEvent.InputTuple,
      RelayerUpdatedEvent.OutputTuple,
      RelayerUpdatedEvent.OutputObject
    >;
  };
}
